// City database for intelligent location recognition
export interface CityInfo {
  city: string;
  state: string;
  country: string;
  aliases?: string[];
}

export const CITY_DATABASE: CityInfo[] = [
  // Major US Cities
  { city: "New York", state: "New York", country: "USA", aliases: ["nyc", "new york city", "manhattan"] },
  { city: "Los Angeles", state: "California", country: "USA", aliases: ["la", "los angeles"] },
  { city: "Chicago", state: "Illinois", country: "USA", aliases: ["chi", "chicago"] },
  { city: "Houston", state: "Texas", country: "USA", aliases: ["houston"] },
  { city: "Phoenix", state: "Arizona", country: "USA", aliases: ["phoenix"] },
  { city: "Philadelphia", state: "Pennsylvania", country: "USA", aliases: ["philly", "philadelphia"] },
  { city: "San Antonio", state: "Texas", country: "USA", aliases: ["san antonio"] },
  { city: "San Diego", state: "California", country: "USA", aliases: ["san diego"] },
  { city: "Dallas", state: "Texas", country: "USA", aliases: ["dallas"] },
  { city: "Austin", state: "Texas", country: "USA", aliases: ["austin"] },
  { city: "San Jose", state: "California", country: "USA", aliases: ["san jose"] },
  { city: "Fort Worth", state: "Texas", country: "USA", aliases: ["fort worth"] },
  { city: "Jacksonville", state: "Florida", country: "USA", aliases: ["jacksonville"] },
  { city: "Columbus", state: "Ohio", country: "USA", aliases: ["columbus"] },
  { city: "Charlotte", state: "North Carolina", country: "USA", aliases: ["charlotte"] },
  { city: "San Francisco", state: "California", country: "USA", aliases: ["sf", "san francisco", "san fran"] },
  { city: "Indianapolis", state: "Indiana", country: "USA", aliases: ["indianapolis", "indy"] },
  { city: "Seattle", state: "Washington", country: "USA", aliases: ["seattle"] },
  { city: "Denver", state: "Colorado", country: "USA", aliases: ["denver"] },
  { city: "Boston", state: "Massachusetts", country: "USA", aliases: ["boston"] },
  { city: "El Paso", state: "Texas", country: "USA", aliases: ["el paso"] },
  { city: "Detroit", state: "Michigan", country: "USA", aliases: ["detroit"] },
  { city: "Nashville", state: "Tennessee", country: "USA", aliases: ["nashville", "music city"] },
  { city: "Portland", state: "Oregon", country: "USA", aliases: ["portland"] },
  { city: "Memphis", state: "Tennessee", country: "USA", aliases: ["memphis"] },
  { city: "Oklahoma City", state: "Oklahoma", country: "USA", aliases: ["oklahoma city", "okc"] },
  { city: "Las Vegas", state: "Nevada", country: "USA", aliases: ["vegas", "las vegas"] },
  { city: "Louisville", state: "Kentucky", country: "USA", aliases: ["louisville"] },
  { city: "Baltimore", state: "Maryland", country: "USA", aliases: ["baltimore"] },
  { city: "Milwaukee", state: "Wisconsin", country: "USA", aliases: ["milwaukee"] },
  { city: "Albuquerque", state: "New Mexico", country: "USA", aliases: ["albuquerque"] },
  { city: "Tucson", state: "Arizona", country: "USA", aliases: ["tucson"] },
  { city: "Fresno", state: "California", country: "USA", aliases: ["fresno"] },
  { city: "Mesa", state: "Arizona", country: "USA", aliases: ["mesa"] },
  { city: "Sacramento", state: "California", country: "USA", aliases: ["sacramento"] },
  { city: "Atlanta", state: "Georgia", country: "USA", aliases: ["atlanta"] },
  { city: "Kansas City", state: "Missouri", country: "USA", aliases: ["kansas city", "kc"] },
  { city: "Colorado Springs", state: "Colorado", country: "USA", aliases: ["colorado springs"] },
  { city: "Miami", state: "Florida", country: "USA", aliases: ["miami"] },
  { city: "Raleigh", state: "North Carolina", country: "USA", aliases: ["raleigh"] },
  { city: "Omaha", state: "Nebraska", country: "USA", aliases: ["omaha"] },
  { city: "Long Beach", state: "California", country: "USA", aliases: ["long beach"] },
  { city: "Virginia Beach", state: "Virginia", country: "USA", aliases: ["virginia beach"] },
  { city: "Oakland", state: "California", country: "USA", aliases: ["oakland"] },
  { city: "Minneapolis", state: "Minnesota", country: "USA", aliases: ["minneapolis"] },
  { city: "Tampa", state: "Florida", country: "USA", aliases: ["tampa"] },
  { city: "Tulsa", state: "Oklahoma", country: "USA", aliases: ["tulsa"] },
  { city: "New Orleans", state: "Louisiana", country: "USA", aliases: ["new orleans", "nola"] },
  { city: "Arlington", state: "Texas", country: "USA", aliases: ["arlington"] },
  { city: "Honolulu", state: "Hawaii", country: "USA", aliases: ["honolulu"] },
  { city: "Anaheim", state: "California", country: "USA", aliases: ["anaheim"] },
  { city: "Santa Ana", state: "California", country: "USA", aliases: ["santa ana"] },
  { city: "St. Louis", state: "Missouri", country: "USA", aliases: ["saint louis", "st louis", "st. louis"] },
  { city: "Riverside", state: "California", country: "USA", aliases: ["riverside"] },
  { city: "Corpus Christi", state: "Texas", country: "USA", aliases: ["corpus christi"] },
  { city: "Lexington", state: "Kentucky", country: "USA", aliases: ["lexington"] },
  { city: "Pittsburgh", state: "Pennsylvania", country: "USA", aliases: ["pittsburgh"] },
  { city: "Anchorage", state: "Alaska", country: "USA", aliases: ["anchorage"] },
  { city: "Stockton", state: "California", country: "USA", aliases: ["stockton"] },
  { city: "Cincinnati", state: "Ohio", country: "USA", aliases: ["cincinnati"] },
  { city: "St. Paul", state: "Minnesota", country: "USA", aliases: ["saint paul", "st paul", "st. paul"] },
  { city: "Toledo", state: "Ohio", country: "USA", aliases: ["toledo"] },
  { city: "Greensboro", state: "North Carolina", country: "USA", aliases: ["greensboro"] },
  { city: "Newark", state: "New Jersey", country: "USA", aliases: ["newark"] },
  { city: "Plano", state: "Texas", country: "USA", aliases: ["plano"] },
  { city: "Henderson", state: "Nevada", country: "USA", aliases: ["henderson"] },
  { city: "Lincoln", state: "Nebraska", country: "USA", aliases: ["lincoln"] },
  { city: "Buffalo", state: "New York", country: "USA", aliases: ["buffalo"] },
  { city: "Jersey City", state: "New Jersey", country: "USA", aliases: ["jersey city"] },
  { city: "Chula Vista", state: "California", country: "USA", aliases: ["chula vista"] },
  { city: "Fort Wayne", state: "Indiana", country: "USA", aliases: ["fort wayne"] },
  { city: "Orlando", state: "Florida", country: "USA", aliases: ["orlando"] },
  { city: "St. Petersburg", state: "Florida", country: "USA", aliases: ["saint petersburg", "st petersburg", "st. petersburg"] },
  { city: "Chandler", state: "Arizona", country: "USA", aliases: ["chandler"] },
  { city: "Laredo", state: "Texas", country: "USA", aliases: ["laredo"] },
  { city: "Norfolk", state: "Virginia", country: "USA", aliases: ["norfolk"] },
  { city: "Durham", state: "North Carolina", country: "USA", aliases: ["durham"] },
  { city: "Madison", state: "Wisconsin", country: "USA", aliases: ["madison"] },
  { city: "Lubbock", state: "Texas", country: "USA", aliases: ["lubbock"] },
  { city: "Irvine", state: "California", country: "USA", aliases: ["irvine"] },
  { city: "Winston-Salem", state: "North Carolina", country: "USA", aliases: ["winston salem", "winston-salem"] },
  { city: "Glendale", state: "Arizona", country: "USA", aliases: ["glendale"] },
  { city: "Garland", state: "Texas", country: "USA", aliases: ["garland"] },
  { city: "Hialeah", state: "Florida", country: "USA", aliases: ["hialeah"] },
  { city: "Reno", state: "Nevada", country: "USA", aliases: ["reno"] },
  { city: "Chesapeake", state: "Virginia", country: "USA", aliases: ["chesapeake"] },
  { city: "Gilbert", state: "Arizona", country: "USA", aliases: ["gilbert"] },
  { city: "Baton Rouge", state: "Louisiana", country: "USA", aliases: ["baton rouge"] },
  { city: "Irving", state: "Texas", country: "USA", aliases: ["irving"] },
  { city: "Scottsdale", state: "Arizona", country: "USA", aliases: ["scottsdale"] },
  { city: "North Las Vegas", state: "Nevada", country: "USA", aliases: ["north las vegas"] },
  { city: "Fremont", state: "California", country: "USA", aliases: ["fremont"] },
  { city: "Boise", state: "Idaho", country: "USA", aliases: ["boise"] },
  { city: "Richmond", state: "Virginia", country: "USA", aliases: ["richmond"] },
  { city: "San Bernardino", state: "California", country: "USA", aliases: ["san bernardino"] },
  { city: "Birmingham", state: "Alabama", country: "USA", aliases: ["birmingham"] },
  { city: "Spokane", state: "Washington", country: "USA", aliases: ["spokane"] },
  { city: "Rochester", state: "New York", country: "USA", aliases: ["rochester"] },
  { city: "Des Moines", state: "Iowa", country: "USA", aliases: ["des moines"] },
  { city: "Modesto", state: "California", country: "USA", aliases: ["modesto"] },
  { city: "Fayetteville", state: "North Carolina", country: "USA", aliases: ["fayetteville"] },
  { city: "Tacoma", state: "Washington", country: "USA", aliases: ["tacoma"] },
  { city: "Oxnard", state: "California", country: "USA", aliases: ["oxnard"] },
  { city: "Fontana", state: "California", country: "USA", aliases: ["fontana"] },
  { city: "Columbus", state: "Georgia", country: "USA", aliases: ["columbus ga"] },
  { city: "Montgomery", state: "Alabama", country: "USA", aliases: ["montgomery"] },
  { city: "Moreno Valley", state: "California", country: "USA", aliases: ["moreno valley"] },
  { city: "Shreveport", state: "Louisiana", country: "USA", aliases: ["shreveport"] },
  { city: "Aurora", state: "Colorado", country: "USA", aliases: ["aurora"] },
  { city: "Yonkers", state: "New York", country: "USA", aliases: ["yonkers"] },
  { city: "Akron", state: "Ohio", country: "USA", aliases: ["akron"] },
  { city: "Huntington Beach", state: "California", country: "USA", aliases: ["huntington beach"] },
  { city: "Little Rock", state: "Arkansas", country: "USA", aliases: ["little rock"] },
  { city: "Augusta", state: "Georgia", country: "USA", aliases: ["augusta"] },
  { city: "Amarillo", state: "Texas", country: "USA", aliases: ["amarillo"] },
  { city: "Glendale", state: "California", country: "USA", aliases: ["glendale ca"] },
  { city: "Mobile", state: "Alabama", country: "USA", aliases: ["mobile"] },
  { city: "Grand Rapids", state: "Michigan", country: "USA", aliases: ["grand rapids"] },
  { city: "Salt Lake City", state: "Utah", country: "USA", aliases: ["salt lake city", "slc"] },
  { city: "Tallahassee", state: "Florida", country: "USA", aliases: ["tallahassee"] },
  { city: "Huntsville", state: "Alabama", country: "USA", aliases: ["huntsville"] },
  { city: "Grand Prairie", state: "Texas", country: "USA", aliases: ["grand prairie"] },
  { city: "Knoxville", state: "Tennessee", country: "USA", aliases: ["knoxville"] },
  { city: "Worcester", state: "Massachusetts", country: "USA", aliases: ["worcester"] },
  { city: "Newport News", state: "Virginia", country: "USA", aliases: ["newport news"] },
  { city: "Brownsville", state: "Texas", country: "USA", aliases: ["brownsville"] },
  { city: "Overland Park", state: "Kansas", country: "USA", aliases: ["overland park"] },
  { city: "Santa Clarita", state: "California", country: "USA", aliases: ["santa clarita"] },
  { city: "Providence", state: "Rhode Island", country: "USA", aliases: ["providence"] },
  { city: "Garden Grove", state: "California", country: "USA", aliases: ["garden grove"] },
  { city: "Chattanooga", state: "Tennessee", country: "USA", aliases: ["chattanooga"] },
  { city: "Oceanside", state: "California", country: "USA", aliases: ["oceanside"] },
  { city: "Jackson", state: "Mississippi", country: "USA", aliases: ["jackson"] },
  { city: "Fort Lauderdale", state: "Florida", country: "USA", aliases: ["fort lauderdale"] },
  { city: "Santa Rosa", state: "California", country: "USA", aliases: ["santa rosa"] },
  { city: "Rancho Cucamonga", state: "California", country: "USA", aliases: ["rancho cucamonga"] },
  { city: "Port St. Lucie", state: "Florida", country: "USA", aliases: ["port st lucie", "port saint lucie"] },
  { city: "Tempe", state: "Arizona", country: "USA", aliases: ["tempe"] },
  { city: "Ontario", state: "California", country: "USA", aliases: ["ontario"] },
  { city: "Vancouver", state: "Washington", country: "USA", aliases: ["vancouver wa"] },
  { city: "Cape Coral", state: "Florida", country: "USA", aliases: ["cape coral"] },
  { city: "Sioux Falls", state: "South Dakota", country: "USA", aliases: ["sioux falls"] },
  { city: "Springfield", state: "Missouri", country: "USA", aliases: ["springfield mo"] },
  { city: "Peoria", state: "Arizona", country: "USA", aliases: ["peoria az"] },
  { city: "Pembroke Pines", state: "Florida", country: "USA", aliases: ["pembroke pines"] },
  { city: "Elk Grove", state: "California", country: "USA", aliases: ["elk grove"] },
  { city: "Corona", state: "California", country: "USA", aliases: ["corona"] },
  { city: "Lancaster", state: "California", country: "USA", aliases: ["lancaster"] },
  { city: "Eugene", state: "Oregon", country: "USA", aliases: ["eugene"] },
  { city: "Palmdale", state: "California", country: "USA", aliases: ["palmdale"] },
  { city: "Salinas", state: "California", country: "USA", aliases: ["salinas"] },
  { city: "Springfield", state: "Massachusetts", country: "USA", aliases: ["springfield ma"] },
  { city: "Pasadena", state: "California", country: "USA", aliases: ["pasadena"] },
  { city: "Fort Collins", state: "Colorado", country: "USA", aliases: ["fort collins"] },
  { city: "Hayward", state: "California", country: "USA", aliases: ["hayward"] },
  { city: "Pomona", state: "California", country: "USA", aliases: ["pomona"] },
  { city: "Cary", state: "North Carolina", country: "USA", aliases: ["cary"] },
  { city: "Rockford", state: "Illinois", country: "USA", aliases: ["rockford"] },
  { city: "Alexandria", state: "Virginia", country: "USA", aliases: ["alexandria"] },
  { city: "Escondido", state: "California", country: "USA", aliases: ["escondido"] },
  { city: "McKinney", state: "Texas", country: "USA", aliases: ["mckinney"] },
  { city: "Kansas City", state: "Kansas", country: "USA", aliases: ["kansas city ks"] },
  { city: "Joliet", state: "Illinois", country: "USA", aliases: ["joliet"] },
  { city: "Sunnyvale", state: "California", country: "USA", aliases: ["sunnyvale"] },
  { city: "Torrance", state: "California", country: "USA", aliases: ["torrance"] },
  { city: "Bridgeport", state: "Connecticut", country: "USA", aliases: ["bridgeport"] },
  { city: "Lakewood", state: "Colorado", country: "USA", aliases: ["lakewood"] },
  { city: "Hollywood", state: "Florida", country: "USA", aliases: ["hollywood"] },
  { city: "Paterson", state: "New Jersey", country: "USA", aliases: ["paterson"] },
  { city: "Naperville", state: "Illinois", country: "USA", aliases: ["naperville"] },
  { city: "Syracuse", state: "New York", country: "USA", aliases: ["syracuse"] },
  { city: "Mesquite", state: "Texas", country: "USA", aliases: ["mesquite"] },
  { city: "Dayton", state: "Ohio", country: "USA", aliases: ["dayton"] },
  { city: "Savannah", state: "Georgia", country: "USA", aliases: ["savannah"] },
  { city: "Clarksville", state: "Tennessee", country: "USA", aliases: ["clarksville"] },
  { city: "Orange", state: "California", country: "USA", aliases: ["orange"] },
  { city: "Pasadena", state: "Texas", country: "USA", aliases: ["pasadena tx"] },
  { city: "Fullerton", state: "California", country: "USA", aliases: ["fullerton"] },
  { city: "Killeen", state: "Texas", country: "USA", aliases: ["killeen"] },
  { city: "Frisco", state: "Texas", country: "USA", aliases: ["frisco"] },
  { city: "Hampton", state: "Virginia", country: "USA", aliases: ["hampton"] },
  { city: "McAllen", state: "Texas", country: "USA", aliases: ["mcallen"] },
  { city: "Warren", state: "Michigan", country: "USA", aliases: ["warren"] },
  { city: "Bellevue", state: "Washington", country: "USA", aliases: ["bellevue"] },
  { city: "West Valley City", state: "Utah", country: "USA", aliases: ["west valley city"] },
  { city: "Columbia", state: "South Carolina", country: "USA", aliases: ["columbia sc"] },
  { city: "Olathe", state: "Kansas", country: "USA", aliases: ["olathe"] },
  { city: "Sterling Heights", state: "Michigan", country: "USA", aliases: ["sterling heights"] },
  { city: "New Haven", state: "Connecticut", country: "USA", aliases: ["new haven"] },
  { city: "Miramar", state: "Florida", country: "USA", aliases: ["miramar"] },
  { city: "Waco", state: "Texas", country: "USA", aliases: ["waco"] },
  { city: "Thousand Oaks", state: "California", country: "USA", aliases: ["thousand oaks"] },
  { city: "Cedar Rapids", state: "Iowa", country: "USA", aliases: ["cedar rapids"] },
  { city: "Charleston", state: "South Carolina", country: "USA", aliases: ["charleston"] },
  { city: "Visalia", state: "California", country: "USA", aliases: ["visalia"] },
  { city: "Topeka", state: "Kansas", country: "USA", aliases: ["topeka"] },
  { city: "Elizabeth", state: "New Jersey", country: "USA", aliases: ["elizabeth"] },
  { city: "Gainesville", state: "Florida", country: "USA", aliases: ["gainesville"] },
  { city: "Thornton", state: "Colorado", country: "USA", aliases: ["thornton"] },
  { city: "Roseville", state: "California", country: "USA", aliases: ["roseville"] },
  { city: "Carrollton", state: "Texas", country: "USA", aliases: ["carrollton"] },
  { city: "Coral Springs", state: "Florida", country: "USA", aliases: ["coral springs"] },
  { city: "Stamford", state: "Connecticut", country: "USA", aliases: ["stamford"] },
  { city: "Simi Valley", state: "California", country: "USA", aliases: ["simi valley"] },
  { city: "Concord", state: "California", country: "USA", aliases: ["concord"] },
  { city: "Hartford", state: "Connecticut", country: "USA", aliases: ["hartford"] },
  { city: "Kent", state: "Washington", country: "USA", aliases: ["kent"] },
  { city: "Lafayette", state: "Louisiana", country: "USA", aliases: ["lafayette"] },
  { city: "Midland", state: "Texas", country: "USA", aliases: ["midland"] },
  { city: "Surprise", state: "Arizona", country: "USA", aliases: ["surprise"] },
  { city: "Denton", state: "Texas", country: "USA", aliases: ["denton"] },
  { city: "Victorville", state: "California", country: "USA", aliases: ["victorville"] },
  { city: "Evansville", state: "Indiana", country: "USA", aliases: ["evansville"] },
  { city: "Santa Clara", state: "California", country: "USA", aliases: ["santa clara"] },
  { city: "Abilene", state: "Texas", country: "USA", aliases: ["abilene"] },
  { city: "Athens", state: "Georgia", country: "USA", aliases: ["athens"] },
  { city: "Vallejo", state: "California", country: "USA", aliases: ["vallejo"] },
  { city: "Allentown", state: "Pennsylvania", country: "USA", aliases: ["allentown"] },
  { city: "Norman", state: "Oklahoma", country: "USA", aliases: ["norman"] },
  { city: "Beaumont", state: "Texas", country: "USA", aliases: ["beaumont"] },
  { city: "Independence", state: "Missouri", country: "USA", aliases: ["independence"] },
  { city: "Murfreesboro", state: "Tennessee", country: "USA", aliases: ["murfreesboro"] },
  { city: "Ann Arbor", state: "Michigan", country: "USA", aliases: ["ann arbor"] },
  { city: "Springfield", state: "Illinois", country: "USA", aliases: ["springfield il"] },
  { city: "Berkeley", state: "California", country: "USA", aliases: ["berkeley"] },
  { city: "Peoria", state: "Illinois", country: "USA", aliases: ["peoria il"] },
  { city: "Provo", state: "Utah", country: "USA", aliases: ["provo"] },
  { city: "El Monte", state: "California", country: "USA", aliases: ["el monte"] },
  { city: "Columbia", state: "Missouri", country: "USA", aliases: ["columbia mo"] },
  { city: "Lansing", state: "Michigan", country: "USA", aliases: ["lansing"] },
  { city: "Fargo", state: "North Dakota", country: "USA", aliases: ["fargo"] },
  { city: "Downey", state: "California", country: "USA", aliases: ["downey"] },
  { city: "Costa Mesa", state: "California", country: "USA", aliases: ["costa mesa"] },
  { city: "Wilmington", state: "North Carolina", country: "USA", aliases: ["wilmington"] },
  { city: "Arvada", state: "Colorado", country: "USA", aliases: ["arvada"] },
  { city: "Inglewood", state: "California", country: "USA", aliases: ["inglewood"] },
  { city: "Miami Gardens", state: "Florida", country: "USA", aliases: ["miami gardens"] },
  { city: "Carlsbad", state: "California", country: "USA", aliases: ["carlsbad"] },
  { city: "Westminster", state: "Colorado", country: "USA", aliases: ["westminster"] },
  { city: "Rochester", state: "Minnesota", country: "USA", aliases: ["rochester mn"] },
  { city: "Odessa", state: "Texas", country: "USA", aliases: ["odessa"] },
  { city: "Manchester", state: "New Hampshire", country: "USA", aliases: ["manchester"] },
  { city: "Elgin", state: "Illinois", country: "USA", aliases: ["elgin"] },
  { city: "West Jordan", state: "Utah", country: "USA", aliases: ["west jordan"] },
  { city: "Round Rock", state: "Texas", country: "USA", aliases: ["round rock"] },
  { city: "Clearwater", state: "Florida", country: "USA", aliases: ["clearwater"] },
  { city: "Waterbury", state: "Connecticut", country: "USA", aliases: ["waterbury"] },
  { city: "Gresham", state: "Oregon", country: "USA", aliases: ["gresham"] },
  { city: "Fairfield", state: "California", country: "USA", aliases: ["fairfield"] },
  { city: "Billings", state: "Montana", country: "USA", aliases: ["billings"] },
  { city: "Lowell", state: "Massachusetts", country: "USA", aliases: ["lowell"] },
  { city: "San Buenaventura", state: "California", country: "USA", aliases: ["ventura", "san buenaventura"] },
  { city: "Pueblo", state: "Colorado", country: "USA", aliases: ["pueblo"] },
  { city: "High Point", state: "North Carolina", country: "USA", aliases: ["high point"] },
  { city: "West Covina", state: "California", country: "USA", aliases: ["west covina"] },
  { city: "Richmond", state: "California", country: "USA", aliases: ["richmond ca"] },
  { city: "Murrieta", state: "California", country: "USA", aliases: ["murrieta"] },
  { city: "Cambridge", state: "Massachusetts", country: "USA", aliases: ["cambridge"] },
  { city: "Antioch", state: "California", country: "USA", aliases: ["antioch"] },
  { city: "Temecula", state: "California", country: "USA", aliases: ["temecula"] },
  { city: "Norwalk", state: "California", country: "USA", aliases: ["norwalk"] },
  { city: "Centennial", state: "Colorado", country: "USA", aliases: ["centennial"] },
  { city: "Everett", state: "Washington", country: "USA", aliases: ["everett"] },
  { city: "Palm Bay", state: "Florida", country: "USA", aliases: ["palm bay"] },
  { city: "Wichita Falls", state: "Texas", country: "USA", aliases: ["wichita falls"] },
  { city: "Green Bay", state: "Wisconsin", country: "USA", aliases: ["green bay"] },
  { city: "Daly City", state: "California", country: "USA", aliases: ["daly city"] },
  { city: "Burbank", state: "California", country: "USA", aliases: ["burbank"] },
  { city: "Richardson", state: "Texas", country: "USA", aliases: ["richardson"] },
  { city: "Pompano Beach", state: "Florida", country: "USA", aliases: ["pompano beach"] },
  { city: "North Charleston", state: "South Carolina", country: "USA", aliases: ["north charleston"] },
  { city: "Broken Arrow", state: "Oklahoma", country: "USA", aliases: ["broken arrow"] },
  { city: "Boulder", state: "Colorado", country: "USA", aliases: ["boulder"] },
  { city: "West Palm Beach", state: "Florida", country: "USA", aliases: ["west palm beach"] },
  { city: "Santa Maria", state: "California", country: "USA", aliases: ["santa maria"] },
  { city: "El Cajon", state: "California", country: "USA", aliases: ["el cajon"] },
  { city: "Davenport", state: "Iowa", country: "USA", aliases: ["davenport"] },
  { city: "Rialto", state: "California", country: "USA", aliases: ["rialto"] },
  { city: "Las Cruces", state: "New Mexico", country: "USA", aliases: ["las cruces"] },
  { city: "San Mateo", state: "California", country: "USA", aliases: ["san mateo"] },
  { city: "Lewisville", state: "Texas", country: "USA", aliases: ["lewisville"] },
  { city: "South Bend", state: "Indiana", country: "USA", aliases: ["south bend"] },
  { city: "Lakeland", state: "Florida", country: "USA", aliases: ["lakeland"] },
  { city: "Erie", state: "Pennsylvania", country: "USA", aliases: ["erie"] },
  { city: "Tyler", state: "Texas", country: "USA", aliases: ["tyler"] },
  { city: "Pearland", state: "Texas", country: "USA", aliases: ["pearland"] },
  { city: "College Station", state: "Texas", country: "USA", aliases: ["college station"] },
  { city: "Kenosha", state: "Wisconsin", country: "USA", aliases: ["kenosha"] },
  { city: "Sandy Springs", state: "Georgia", country: "USA", aliases: ["sandy springs"] },
  { city: "Clovis", state: "California", country: "USA", aliases: ["clovis"] },
  { city: "Flint", state: "Michigan", country: "USA", aliases: ["flint"] },
  { city: "Columbia", state: "Maryland", country: "USA", aliases: ["columbia md"] },
  { city: "El Paso", state: "Texas", country: "USA", aliases: ["el paso"] },
  { city: "Tustin", state: "California", country: "USA", aliases: ["tustin"] },
  { city: "Roseville", state: "Michigan", country: "USA", aliases: ["roseville mi"] },
  { city: "Duluth", state: "Minnesota", country: "USA", aliases: ["duluth"] },
  { city: "Albany", state: "New York", country: "USA", aliases: ["albany"] },
  { city: "Kirkland", state: "Washington", country: "USA", aliases: ["kirkland"] },
  { city: "Kennewick", state: "Washington", country: "USA", aliases: ["kennewick"] },
  { city: "Menifee", state: "California", country: "USA", aliases: ["menifee"] },
  { city: "Macon", state: "Georgia", country: "USA", aliases: ["macon"] },
  { city: "Baldwin Park", state: "California", country: "USA", aliases: ["baldwin park"] },
  { city: "Chino", state: "California", country: "USA", aliases: ["chino"] },
  { city: "Bloomington", state: "Minnesota", country: "USA", aliases: ["bloomington mn"] },
  { city: "Compton", state: "California", country: "USA", aliases: ["compton"] },
  { city: "Beaumont", state: "California", country: "USA", aliases: ["beaumont ca"] },
  { city: "Amherst", state: "New York", country: "USA", aliases: ["amherst"] },
  { city: "Albany", state: "Georgia", country: "USA", aliases: ["albany ga"] },
  { city: "Brockton", state: "Massachusetts", country: "USA", aliases: ["brockton"] },
  { city: "Renton", state: "Washington", country: "USA", aliases: ["renton"] },
  { city: "Mission Viejo", state: "California", country: "USA", aliases: ["mission viejo"] },
  { city: "Redding", state: "California", country: "USA", aliases: ["redding"] },
  { city: "Chino Hills", state: "California", country: "USA", aliases: ["chino hills"] },
  { city: "Buena Park", state: "California", country: "USA", aliases: ["buena park"] },
  { city: "San Marcos", state: "California", country: "USA", aliases: ["san marcos"] },
  { city: "Livonia", state: "Michigan", country: "USA", aliases: ["livonia"] },
  { city: "Fall River", state: "Massachusetts", country: "USA", aliases: ["fall river"] },
  { city: "Redwood City", state: "California", country: "USA", aliases: ["redwood city"] },
  { city: "New Bedford", state: "Massachusetts", country: "USA", aliases: ["new bedford"] },
  { city: "Plantation", state: "Florida", country: "USA", aliases: ["plantation"] },
  { city: "Sandy", state: "Utah", country: "USA", aliases: ["sandy"] },
  { city: "Sunrise", state: "Florida", country: "USA", aliases: ["sunrise"] },
  { city: "Macon-Bibb County", state: "Georgia", country: "USA", aliases: ["macon bibb county"] },
  { city: "San Angelo", state: "Texas", country: "USA", aliases: ["san angelo"] },
  { city: "League City", state: "Texas", country: "USA", aliases: ["league city"] },
  { city: "Lawrence", state: "Kansas", country: "USA", aliases: ["lawrence"] },
  { city: "Santa Barbara", state: "California", country: "USA", aliases: ["santa barbara"] },
  { city: "Plantation", state: "Florida", country: "USA", aliases: ["plantation fl"] },
  { city: "Carson", state: "California", country: "USA", aliases: ["carson"] },

  // International Cities
  { city: "London", state: "", country: "United Kingdom", aliases: ["london"] },
  { city: "Paris", state: "", country: "France", aliases: ["paris"] },
  { city: "Tokyo", state: "", country: "Japan", aliases: ["tokyo"] },
  { city: "Rome", state: "", country: "Italy", aliases: ["rome"] },
  { city: "Barcelona", state: "", country: "Spain", aliases: ["barcelona"] },
  { city: "Amsterdam", state: "", country: "Netherlands", aliases: ["amsterdam"] },
  { city: "Berlin", state: "", country: "Germany", aliases: ["berlin"] },
  { city: "Madrid", state: "", country: "Spain", aliases: ["madrid"] },
  { city: "Lisbon", state: "", country: "Portugal", aliases: ["lisbon"] },
  { city: "Dublin", state: "", country: "Ireland", aliases: ["dublin"] },
  { city: "Prague", state: "", country: "Czech Republic", aliases: ["prague"] },
  { city: "Vienna", state: "", country: "Austria", aliases: ["vienna"] },
  { city: "Athens", state: "", country: "Greece", aliases: ["athens greece"] },
  { city: "Budapest", state: "", country: "Hungary", aliases: ["budapest"] },
  { city: "Stockholm", state: "", country: "Sweden", aliases: ["stockholm"] },
  { city: "Copenhagen", state: "", country: "Denmark", aliases: ["copenhagen"] },
  { city: "Oslo", state: "", country: "Norway", aliases: ["oslo"] },
  { city: "Helsinki", state: "", country: "Finland", aliases: ["helsinki"] },
  { city: "Warsaw", state: "", country: "Poland", aliases: ["warsaw"] },
  { city: "Zurich", state: "", country: "Switzerland", aliases: ["zurich"] },
  { city: "Geneva", state: "", country: "Switzerland", aliases: ["geneva"] },
  { city: "Florence", state: "", country: "Italy", aliases: ["florence"] },
  { city: "Venice", state: "", country: "Italy", aliases: ["venice"] },
  { city: "Milan", state: "", country: "Italy", aliases: ["milan"] },
  { city: "Naples", state: "", country: "Italy", aliases: ["naples"] },
  { city: "Munich", state: "", country: "Germany", aliases: ["munich"] },
  { city: "Frankfurt", state: "", country: "Germany", aliases: ["frankfurt"] },
  { city: "Brussels", state: "", country: "Belgium", aliases: ["brussels"] },
  { city: "Edinburgh", state: "", country: "United Kingdom", aliases: ["edinburgh"] },
  { city: "Manchester", state: "", country: "United Kingdom", aliases: ["manchester uk"] },
  { city: "Liverpool", state: "", country: "United Kingdom", aliases: ["liverpool"] },
  { city: "Birmingham", state: "", country: "United Kingdom", aliases: ["birmingham uk"] },
  { city: "Glasgow", state: "", country: "United Kingdom", aliases: ["glasgow"] },
  { city: "Montreal", state: "", country: "Canada", aliases: ["montreal"] },
  { city: "Toronto", state: "", country: "Canada", aliases: ["toronto"] },
  { city: "Vancouver", state: "", country: "Canada", aliases: ["vancouver canada"] },
  { city: "Sydney", state: "", country: "Australia", aliases: ["sydney"] },
  { city: "Melbourne", state: "", country: "Australia", aliases: ["melbourne"] },
  { city: "Brisbane", state: "", country: "Australia", aliases: ["brisbane"] },
  { city: "Perth", state: "", country: "Australia", aliases: ["perth"] },
  { city: "Adelaide", state: "", country: "Australia", aliases: ["adelaide"] },
  { city: "Auckland", state: "", country: "New Zealand", aliases: ["auckland"] },
  { city: "Wellington", state: "", country: "New Zealand", aliases: ["wellington"] },
  { city: "Bangkok", state: "", country: "Thailand", aliases: ["bangkok"] },
  { city: "Singapore", state: "", country: "Singapore", aliases: ["singapore"] },
  { city: "Hong Kong", state: "", country: "Hong Kong", aliases: ["hong kong"] },
  { city: "Seoul", state: "", country: "South Korea", aliases: ["seoul"] },
  { city: "Beijing", state: "", country: "China", aliases: ["beijing"] },
  { city: "Shanghai", state: "", country: "China", aliases: ["shanghai"] },
  { city: "Mumbai", state: "", country: "India", aliases: ["mumbai"] },
  { city: "Delhi", state: "", country: "India", aliases: ["delhi"] },
  { city: "Bangalore", state: "", country: "India", aliases: ["bangalore", "bengaluru"] },
  { city: "Chennai", state: "", country: "India", aliases: ["chennai"] },
  { city: "Kolkata", state: "", country: "India", aliases: ["kolkata", "calcutta"] },
  { city: "Hyderabad", state: "", country: "India", aliases: ["hyderabad"] },
  { city: "Dubai", state: "", country: "United Arab Emirates", aliases: ["dubai"] },
  { city: "Abu Dhabi", state: "", country: "United Arab Emirates", aliases: ["abu dhabi"] },
  { city: "Doha", state: "", country: "Qatar", aliases: ["doha"] },
  { city: "Kuwait City", state: "", country: "Kuwait", aliases: ["kuwait city"] },
  { city: "Riyadh", state: "", country: "Saudi Arabia", aliases: ["riyadh"] },
  { city: "Jeddah", state: "", country: "Saudi Arabia", aliases: ["jeddah"] },
  { city: "Tel Aviv", state: "", country: "Israel", aliases: ["tel aviv"] },
  { city: "Jerusalem", state: "", country: "Israel", aliases: ["jerusalem"] },
  { city: "Istanbul", state: "", country: "Turkey", aliases: ["istanbul"] },
  { city: "Ankara", state: "", country: "Turkey", aliases: ["ankara"] },
  { city: "Cairo", state: "", country: "Egypt", aliases: ["cairo"] },
  { city: "Alexandria", state: "", country: "Egypt", aliases: ["alexandria egypt"] },
  { city: "Casablanca", state: "", country: "Morocco", aliases: ["casablanca"] },
  { city: "Marrakech", state: "", country: "Morocco", aliases: ["marrakech", "marrakesh"] },
  { city: "Cape Town", state: "", country: "South Africa", aliases: ["cape town"] },
  { city: "Johannesburg", state: "", country: "South Africa", aliases: ["johannesburg"] },
  { city: "Lagos", state: "", country: "Nigeria", aliases: ["lagos"] },
  { city: "Nairobi", state: "", country: "Kenya", aliases: ["nairobi"] },
  { city: "Buenos Aires", state: "", country: "Argentina", aliases: ["buenos aires"] },
  { city: "São Paulo", state: "", country: "Brazil", aliases: ["sao paulo", "são paulo"] },
  { city: "Rio de Janeiro", state: "", country: "Brazil", aliases: ["rio de janeiro", "rio"] },
  { city: "Lima", state: "", country: "Peru", aliases: ["lima"] },
  { city: "Santiago", state: "", country: "Chile", aliases: ["santiago"] },
  { city: "Bogotá", state: "", country: "Colombia", aliases: ["bogota", "bogotá"] },
  { city: "Caracas", state: "", country: "Venezuela", aliases: ["caracas"] },
  { city: "Mexico City", state: "", country: "Mexico", aliases: ["mexico city", "cdmx"] },
  { city: "Cancún", state: "", country: "Mexico", aliases: ["cancun", "cancún"] },
  { city: "Guadalajara", state: "", country: "Mexico", aliases: ["guadalajara"] },
  { city: "Monterrey", state: "", country: "Mexico", aliases: ["monterrey"] },
  { city: "Havana", state: "", country: "Cuba", aliases: ["havana"] },
  { city: "Kingston", state: "", country: "Jamaica", aliases: ["kingston"] },
  { city: "San Juan", state: "", country: "Puerto Rico", aliases: ["san juan"] },
];

export function findCityInfo(input: string): CityInfo | null {
  const lowerInput = input.toLowerCase().trim();

  // Try to find exact match first
  for (const city of CITY_DATABASE) {
    // Check main city name
    if (city.city.toLowerCase() === lowerInput) {
      return city;
    }

    // Check aliases
    if (city.aliases && city.aliases.some(alias => alias.toLowerCase() === lowerInput)) {
      return city;
    }
  }

  // Try partial matches for multi-word cities
  for (const city of CITY_DATABASE) {
    if (city.city.toLowerCase().includes(lowerInput) || lowerInput.includes(city.city.toLowerCase())) {
      return city;
    }

    if (city.aliases) {
      for (const alias of city.aliases) {
        if (alias.toLowerCase().includes(lowerInput) || lowerInput.includes(alias.toLowerCase())) {
          return city;
        }
      }
    }
  }

  return null;
}

export function formatLocation(cityInfo: CityInfo): string {
  if (cityInfo.country === "USA" && cityInfo.state) {
    return `${cityInfo.city}, ${cityInfo.state}`;
  } else if (cityInfo.state) {
    return `${cityInfo.city}, ${cityInfo.state}, ${cityInfo.country}`;
  } else {
    return `${cityInfo.city}, ${cityInfo.country}`;
  }
}